default_language_version:
  python: python3
  node: "18.17.1"
exclude: ^tests/samples/mqt-diffs/.*
repos:
  - repo: local
    hooks:
      - id: poetry-check
        name: poetry check
        entry: poetry
        args: ["check"]
        files: pyproject\.toml$
        pass_filenames: false
        language: system
      - id: forbidden-files
        name: forbidden files
        entry: found forbidden files; remove them
        language: fail
        files: "\\.rej$"
  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        additional_dependencies: ["click<8.1.0"]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args:
          - --keep-percent-format
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear==23.7.10", "importlib-metadata<6.8.0"]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        args: [--ignore-unknown]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-xml
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args:
          - --github
          - --maxlevel=6
          - --title=<summary>Table of contents</summary>
        exclude: ^(tests/|.github/ISSUE_TEMPLATE/)
